version: 2
registries:
  maven-github:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/fp-felles
    username: x-access-token
    password: ${{ secrets.READER_TOKEN }}

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      actions:
        dependency-type: "production"
  - package-ecosystem: maven
    directory: "/"
    registries:
      - maven-github
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    allow:
      - dependency-type: "all"
    groups:
      prod-deps:
        dependency-type: "production"
      dev-deps:
        dependency-type: "development"
