kontrakt:
  - any:
    - changed-files:
      - any-glob-to-any-file: "**/*"
      - any-glob-to-any-file: "!**/*/pom.xml"
      - any-glob-to-any-file: "!pom.xml"

pom:
  - any:
    - changed-files:
      - any-glob-to-any-file: "**/*/pom.xml"
      - any-glob-to-any-file: "pom.xml"
