package no.nav.foreldrepenger.kontrakter.fpoversikt.inntektsmelding;

public enum NaturalytelseType {
    ELEKTRISK_KOMMUNIKASJON,
    AKSJER_GRUNNFONDSBEVIS_TIL_UNDERKURS,
    LOSJI,
    KOST_DØGN,
    BESØKSREISER_HJEMMET_ANNET,
    KOSTBESPARELSE_I_HJEMMET,
    RENTEFORDEL_LÅN,
    BIL,
    KOST_DAGER,
    BOLIG,
    SKATTEPLIKTIG_DEL_FORSIKRINGER,
    FRI_TRANSPORT,
    OPSJONER,
    TILSKUDD_BARNEHAGEPLASS,
    ANNET,
    BEDRIFTSBARNEHAGEPLASS,
    YRKEBIL_TJENESTLIGBEHOV_KILOMETER,
    YRKEBIL_TJENESTLIGBEHOV_LISTEPRIS,
    INNBETALING_TIL_UTENLANDSK_PENSJONSORDNING,
}
