name: Publish kontrakt
on:
  release:
    types: [published]

jobs:
  build:
    name: Bygg pull-request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
        with:
          ref: 'master'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Publish artifacts
        shell: bash
        run: |
           mvn -B versions:set -DnewVersion="$NEW_VERSION" -DgenerateBackupPoms=false
           mvn deploy -e --batch-mode --settings ./.github/.m2/settings.xml -DtrimStackTrace=false -Drevision="$NEW_VERSION" -Dfile.encoding=UTF-8
        env:
          GH_ACCESS_TOKEN : ${{ secrets.GH_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          NEW_VERSION: ${{ github.event.release.tag_name }}
